
CREATED = 'CREATED'
CONNECTED = 'CONNECTED'
DISCONNECTED = 'DISCONNECTED'
NICK = 'NICK'
USER = 'USER'
PING = 'PING'
PONG = 'PONG'
JOIN = 'JOIN'
PART = 'PART'
QUIT = 'QUIT'
PRIVMSG = 'PRIVMSG'
NOTICE = 'NOTICE'

