
CREATED = u'CREATED'
CONNECTED = u'CONNECTED'
DISCONNECTED = u'DISCONNECTED'
NICK = u'NICK'
USER = u'USER'
PING = u'PING'
PONG = u'PONG'
JOIN = u'JOIN'
PART = u'PART'
QUIT = u'QUIT'
PRIVMSG = u'PRIVMSG'
NOTICE = u'NOTICE'

